version: "1"
services:

  hdctbet:
    image: rhnode/hdctbet:latest
    build: .
    ports:
      - "8010:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
