version: "1"
services:

  hdctbet:
    image: rhnode/hdctbet:latest
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  