version: "1"
services:

  flirt:
    image: rhnode/flirt:latest
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: []
    expose:
      - "8000"
      
    labels:
      - "traefik.http.routers.flirt.rule=PathPrefix(`/flirt`)"