name: Build+push manager image on release

on:
  release:
    types:
      - published

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check disk space
        run: df . -h
      - name: Identify node
        id: step1
        run: |
          VAL=${{github.event.release.tag_name}}
          echo "::set-output name=valid::true"
          if [[ "$VAL" == zerodose-* ]]; then
            echo "::set-output name=dir::nodes/zerodose"
            echo "::set-output name=image_name::zerodose"
          elif [[ "$VAL" == hdbet-* ]]; then
            echo "::set-output name=dir::nodes/hdbet"
            echo "::set-output name=image_name::hdbet"
          elif [[ "$VAL" == hdctbet-* ]]; then
            echo "::set-output name=dir::nodes/hdctbet"
            echo "::set-output name=image_name::hdctbet"
          elif [[ "$VAL" == amyloidai-* ]]; then
            echo "::set-output name=dir::nodes/amyloidAI"
            echo "::set-output name=image_name::amyloidai"
          elif [[ "$VAL" == aims-* ]]; then
            echo "::set-output name=dir::nodes/aims"
            echo "::set-output name=image_name::aims"
          elif [[ "$VAL" == totalsegmentator-* ]]; then
            echo "::set-output name=dir::nodes/totalsegmentator"
            echo "::set-output name=image_name::totalsegmentator"
          elif [[ "$VAL" == flirt-* ]]; then
            echo "::set-output name=dir::nodes/flirt"
            echo "::set-output name=image_name::flirt"
          elif [[ "$VAL" == reorient2std-* ]]; then
            echo "::set-output name=dir::nodes/reorient2std"
            echo "::set-output name=image_name::reorient2std"
          elif [[ "$VAL" == fslmaths-* ]]; then
            echo "::set-output name=dir::nodes/fslmaths"
            echo "::set-output name=image_name::fslmaths"
          elif [[ "$VAL" == convertxfm-* ]]; then
            echo "::set-output name=dir::nodes/convertXFM"
            echo "::set-output name=image_name::convertxfm"
          elif [[ "$VAL" == brainpetnr-* ]]; then
            echo "::set-output name=dir::nodes/brainPETNR"
            echo "::set-output name=image_name::brainpetnr"
          elif [[ "$VAL" == pe2idenoiser-* ]]; then
            echo "::set-output name=dir::nodes/pe2idenoiser"
            echo "::set-output name=image_name::pe2idenoiser"
          elif [[ "$VAL" == zerodose_dicom-* ]]; then
            echo "::set-output name=dir::dicom_nodes/zerodose"
            echo "::set-output name=image_name::zerodose_dicom"
          else
            echo "::set-output name=valid::false"
          fi
      - name: Split branch name
        if : ${{steps.step1.outputs.valid == 'true'}}
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        id: split
        run: echo "::set-output name=version::${TAG_NAME##*-}"
      - 
        name: Set up QEMU
        if : ${{steps.step1.outputs.valid == 'true'}}
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        if : ${{steps.step1.outputs.valid == 'true'}}
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        if : ${{steps.step1.outputs.valid == 'true'}}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        if : ${{steps.step1.outputs.valid == 'true'}}
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:${{steps.step1.outputs.dir}}"
          push: true
          tags: rhnode/${{steps.step1.outputs.image_name}}:${{ steps.split.outputs.version }}
          
