name: Build+push manager image on release

on:
  release:
    types:
      - published

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ 
          {release_identifier: zerodose_dicom, dir: dicom_nodes/zerodose, image_name: zerodose_dicom}, 
          {release_identifier: zerodose, dir: nodes/zerodose, image_name: zerodose}, 
          {release_identifier: hdbet, dir: nodes/hdbet, image_name: hdbet}, 
        ]


    steps:
      - name: Split branch name
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        id: split
        run: echo "::set-output name=version::${TAG_NAME##*-}"
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:{{matrix.node.dir}}"
          push: true
          tags: rhnode/{{matrix.node.image_name}}:${{ steps.split.outputs.version }}
          
